# -*- coding: utf-8 -*-
playlist_map = { 'Discover Weekly': 
   [ 'Soundclash ~ Flosstradamus|TroyBoi|',
     'Rage the Night Away ~ Waka Flocka Flame|',
     'Acid Youths (Legalize It!!) ~ David Heartbreak|Simon Sayz|Feral Is Kinky|',
     'Kanye ~ The Chainsmokers|sirenXX|',
     'Hands in the Air ~ Sire Castro|',
     'You\'re On ~ Madeon|Kyan|',
     'Inspire - Jai Wolf Remix ~ Gazzo|Farewell Luna|',
     'Belong to the Rhythm - Original Mix ~ King Arthur|Michael Meaco|',
     'Are We Faded - Original Mix ~ Keys N Krates|',
     'All I Want (Diplo Remix) ~ Dawn Golden|',
     'Dangerous - Oliver Remix ~ Big Data|',
     'Changing Me (Extended) ~ Bobby Green|',
     'I Don\'t Like It, I Love It (feat. Robin Thicke & Verdine White) ~ Flo Rida|Robin Thicke|Verdine White|',
     'Night Lights ~ K Theory|',
     'I Heart U ~ Bad Paris|',
     'Waves - Robin Schulz Remix ~ Mr. Probz|Chris Brown|T.I.|',
     'Fly - Original Mix ~ San Holo|',
     'Tremor ~ Dimitri Vegas & Like Mike|Martin Garrix|Like Mike|',
     'This Could Be Love - Radio Edit ~ Borgeous|Shaun Frank|Delaney Jane|',
     'Where Are Ü Now (with Justin Bieber) - Rustie Remix ~ Jack Ü|Skrillex|Diplo|Justin Bieber|',
     'One Touch (feat. AlunaGeorge and Rae Sremmurd) ~ Baauer|AlunaGeorge|Rae Sremmurd|',
     'Bitch I\'m Madonna ~ Madonna|Nicki Minaj|',
     'Feel Good ~ Stony|',
     'Heavy Crown ~ Iggy Azalea|Ellie Goulding|',
     'Help Our Souls (Urban Contact Radio Edit) ~ Nihils|',
     'Can\'t Stop Playing - Oliver Heldens & Gregor Salto Remix ~ DR. KUCHO!|Gregor Salto|',
     'Show You ~ Marshmello|',
     'Ayo ~ Chris Brown|Tyga|',
     'Breathless ft. Michelle Quezada - Regulators Remix ~ Candyland|Regulators|',
     'You Know You Like It - Remix Sound ~ Pete Dawson|' ],
  'Rap [good]': 
   [ 'Str8 Ballin\' ~ 2Pac|',
     'i ~ Kendrick Lamar|',
     'Hate Me Now ~ Nas|Diddy|',
     'Big Poppa ~ The Notorious B.I.G.|',
     'The Blacker The Berry ~ Kendrick Lamar|',
     'Can\'t Get Enough ~ J. Cole|Trey Songz|',
     'All Eyez On Me ~ 2Pac|',
     'IV. Sweatpants ~ Childish Gambino|',
     'Night Riders (feat. Travi$ Scott, 2 Chainz, Pusha T & Mad Cobra) ~ Major Lazer|',
     'King Kunta ~ Kendrick Lamar|',
     'Ambitionz Az A Ridah ~ 2Pac|',
     'Dance With the Devil ~ Immortal Technique|',
     'm.A.A.d city ~ Kendrick Lamar|MC Eiht|',
     'A.D.H.D ~ Kendrick Lamar|',
     'Fuck Tha Police ~ N.W.A.|',
     'Hail Mary - (Explicit) ~ 2Pac|',
     'Don\'t Tell \'Em ~ Jeremih|YG|',
     '3005 ~ Childish Gambino|',
     '2 Of Amerikaz Most Wanted - (Explicit) ~ 2Pac|Snoop Dogg|',
     'All Day ~ Kanye West|Theophilus London|Allan Kingdom|Paul McCartney|',
     'Hit \'Em Up - Single Version (Explicit) ~ 2Pac|Outlawz|',
     'III. Telegraph Ave. ("Oakland" by Lloyd) ~ Childish Gambino|',
     'Unchained (The Payback / Untouchable) ~ James Brown|2Pac|',
     'Backseat Freestyle ~ Kendrick Lamar|',
     'Evil Twin ~ Eminem|',
     'Monster ~ Kanye West|JAY Z|Rick Ross|Nicki Minaj|Bon Iver|',
     'The Real Slim Shady ~ Eminem|',
     'Who Gon Stop Me ~ JAY Z|Kanye West|',
     'Swimming Pools (Drank) ~ Kendrick Lamar|',
     'Clique ~ Kanye West|JAY Z|Big Sean|',
     'To Live & Die In L.A. ~ 2Pac|',
     'Bad Guy ~ Eminem|',
     'Bitch, Don’t Kill My Vibe ~ Kendrick Lamar|',
     'Don\'t Like.1 ~ Kanye West|Chief Keef|Pusha T|Big Sean|Jadakiss|',
     'Rap God ~ Eminem|',
     'F**kin\' Problems ~ A$AP Rocky|Drake|2 Chainz|Kendrick Lamar|',
     'Straight Outta Compton ~ N.W.A.|',
     'Through The Wire ~ Kanye West|',
     'The Next Episode ~ Dr. Dre|Snoop Dogg|',
     'Changes - (Explicit) ~ 2Pac|Talent|',
     'Gorgeous ~ Kanye West|Kid Cudi|Raekwon|',
     'Still D.R.E. ~ Dr. Dre|Snoop Dogg|',
     'Stan ~ Eminem|Dido|',
     'Dear Mama ~ 2Pac|',
     'Hey Mama ~ Kanye West|',
     'Ni**as In Paris ~ JAY Z|Kanye West|',
     'Hot N*gga ~ Bobby Shmurda|',
     'California Love (remix) ~ 2Pac|',
     'I Used to Love H.E.R. ~ Common|',
     'H•A•M ~ Kanye West|JAY Z|',
     'So Many Tears - (Explicit) ~ 2Pac|',
     'When Thugz Cry ~ 2Pac|',
     'Ill Mind of Hopsin 5 ~ Hopsin|',
     'All Gold Everything ~ Trinidad James|',
     'I Don\'t Like ~ Chief Keef|Lil Reese|',
     'Gin And Juice ~ Snoop Dogg|',
     'All Of The Lights ~ Kanye West|',
     'Flashing Lights ~ Kanye West|',
     'Picture Me Rollin\' ~ 2Pac|',
     'Only God Can Judge Me ~ 2Pac|',
     'California Love - Original Mix (Explicit) ~ 2Pac|Roger|Dr. Dre|',
     'I Need A Doctor - Explicit Version ~ Dr. Dre|Eminem|Skylar Grey|',
     'On My Level - feat. Too $hort ~ Wiz Khalifa|',
     'Hate Bein\' Sober ~ Chief Keef|50 Cent|Wiz Khalifa|',
     'Tuesday (feat. Drake) ~ I LOVE MAKONNEN|Drake|',
     'Love Sosa ~ Chief Keef|',
     'All Me ~ Drake|2 Chainz|Big Sean|',
     'Black And Yellow ~ Wiz Khalifa|',
     'No Church In The Wild ~ JAY Z|Kanye West|Frank Ocean|The-Dream|',
     'Otis ~ JAY Z|Kanye West|Otis Redding|',
     'Gotta Have It ~ JAY Z|Kanye West|',
     'Hell Of A Life ~ Kanye West|',
     'That\'s My Bitch ~ JAY Z|Kanye West|',
     'Daydreamin\' - feat. Jill Scott ~ Lupe Fiasco|',
     'Murder To Excellence ~ JAY Z|Kanye West|',
     'Homecoming ~ Kanye West|Chris Martin|',
     'Gold Digger ~ Kanye West|Jamie Foxx|',
     'Family Business ~ Kanye West|',
     'Roses ~ Kanye West|',
     'So Appalled ~ Kanye West|JAY Z|Pusha T|Prynce Cy Hi|Swizz Beatz|RZA|',
     'In Da Club ~ 50 Cent|',
     'Dark Fantasy ~ Kanye West|',
     'POWER ~ Kanye West|',
     'Diamonds From Sierra Leone - Remix - Album Version (Explicit) ~ Kanye West|JAY Z|',
     'Headlights ~ Eminem|Nate Ruess|',
     'Won\'t Back Down ~ Eminem Featuring P!nk|P!nk|',
     'New Slaves ~ Kanye West|',
     'Can\'t Tell Me Nothing ~ Kanye West|',
     'Survival ~ Eminem|',
     'I Wonder ~ Kanye West|',
     'Runaway ~ Kanye West|Pusha T|',
     'Rhyme Or Reason ~ Eminem|',
     'Berzerk ~ Eminem|',
     'Good Life ~ Kanye West|T-Pain|',
     'I Am A God ~ Kanye West|God|',
     'Not Afraid ~ Eminem|',
     'Devil In A New Dress ~ Kanye West|Rick Ross|',
     'Lose Yourself - Soundtrack Version ~ Eminem|',
     'Stronger ~ Kanye West|',
     'All Falls Down ~ Kanye West|Syleena Johnson|',
     'Jesus Walks ~ Kanye West|',
     'Love The Way You Lie ~ Eminem|Rihanna|',
     'Heartless ~ Kanye West|',
     'Big Brother ~ Kanye West|',
     'Bound 2 ~ Kanye West|',
     'Guilt Trip ~ Kanye West|',
     'On Sight ~ Kanye West|',
     'Black Skinhead ~ Kanye West|',
     'I\'m In It ~ Kanye West|',
     'Blame Game ~ Kanye West|John Legend|',
     'Blood On The Leaves ~ Kanye West|',
     'Erase Me - Main ~ Kid Cudi|Kanye West|',
     'Asshole ~ Eminem|Skylar Grey|',
     '**Bonus Track** Diamonds From Sierra Leone ~ Kanye West|',
     'Rack City ~ Tyga|',
     'Illest Motherf**ker Alive ~ JAY Z|Kanye West|',
     'Cinderella Man ~ Eminem|',
     'No Love ~ Eminem|Lil Wayne|',
     'Desperation ~ Eminem|Jamie N Commons|',
     'Wicked Ways ~ Eminem|',
     'Work Out ~ J. Cole|',
     'Heartbeat ~ Childish Gambino|',
     'Seven ~ Celph Titled|Demoz|Doap Nixon|Reef The Lost Cauze|King Syze|Chief Kamachi|Planetary|Vinnie Paz|',
     'Lost In The World ~ Kanye West|Bon Iver|' ],
  'Electronic': 
   [ 'Don\'t You Worry Child (feat. John Martin) ~ Swedish House Mafia|John Martin|',
     'Beating of My Heart (Matisse & Sadko Instrumental) [feat. Heidrun] / Sweet Disposition ~ The Temper Trap|M-3ox|Heidrun|',
     'Seeya ~ deadmau5|Colleen D\'agostino|',
     'Beautiful Now ~ Zedd|Jon Bellion|',
     'Never Sleep Alone ~ Kaskade|',
     'When Can I See You Again? ~ Owl City|',
     'How Deep Is Your Love ~ Calvin Harris|Disciples|',
     'The Girl (feat. Cozi Zuehlsdorff) ~ Hellberg|Cozi Zuehlsdorff|',
     'Straight Into The Fire ~ Zedd|',
     'Be Together (feat. Wild Belle) ~ Major Lazer|Wild Belle|',
     'Gecko (Overdrive) - Radio Edit ~ Oliver Heldens|Becky Hill|',
     'To Ü (feat. AlunaGeorge) ~ Jack Ü|Skrillex|Diplo|AlunaGeorge|',
     'Burn ~ KSHMR|DallasK|',
     'Till It Hurts ~ Yellow Claw|Ayden|',
     'Don\'t Stop the Madness ~ Hardwell|W&W|Fatman Scoop|',
     'You\'re No Good (feat. Santigold, Vybz Kartel, Danielle Haim & Yasmin) ~ Major Lazer|',
     'I Still Can\'t Stop ~ Flux Pavilion|',
     'Daisy ~ Zedd|',
     'Addicted To A Memory ~ Zedd|Bahari|',
     'Lean On (feat. MØ & DJ Snake) ~ Major Lazer|MØ|DJ Snake|',
     'Powerful (feat. Ellie Goulding & Tarrus Riley) ~ Major Lazer|Ellie Goulding|Tarrus Riley|',
     'Fireflies - Original Mix ~ John Dahlbäck|Melanie Fontana|',
     'You Know You Like It (Dj Snake Remix) ~ AlunaGeorge|',
     'Five More Hours - Deorro x Chris Brown ~ Deorro|Chris Brown|',
     'I\'m Not Over (feat. Tash) ~ Hellberg|Tash|',
     'Sunrise (feat. Sara Kay) ~ Klaypex|',
     'Prayer In C - Robin Schulz Radio Edit ~ Lilly Wood and The Prick|Robin Schulz|',
     'Blaze Up The Fire (feat. Chronixx) ~ Major Lazer|Chronixx|',
     'Light It Up (feat. Nyla) ~ Major Lazer|Nyla|',
     'Under Your Cloud (Extended Mix) ~ Late Night Alumni|Myon & Shane 54|',
     'Too Original (feat. Elliphant & Jovi Rockwell) ~ Major Lazer|Elliphant|Jovi Rockwell|',
     'Roll the Bass ~ Major Lazer|',
     'Pressure - Alesso Remix ~ Nadia Ali|Starkillers|Alex Kenji|',
     'Infra Turbo Pigcart Racer ~ deadmau5|',
     'I Can\'t Stop ~ Flux Pavilion|',
     'Talking Body - KREAM Remix ~ Tove Lo|',
     'Clarity ~ Zedd|Foxes|',
     'Headlights (feat. Ilsey) ~ Robin Schulz|Ilsey|',
     'Titanium (feat. Sia) ~ David Guetta|Sia|',
     'Collide ~ Hellberg|Deutgen vs Splitbreed|',
     'Insight ~ Haywyre|',
     'Tell Me ~ RL Grime|What So Not|',
     'I Want You To Know ~ Zedd|Selena Gomez|',
     'Runaway (U & I) ~ Galantis|',
     'Real Love (feat. Danyka Nadeau) ~ Rootkit|Danyka Nadeau|',
     'City Of Dreams - Radio Edit ~ Dirty South|Alesso|Ruben Haze|',
     'You Know You Like It ~ DJ Snake & AlunaGeorge|',
     'Crave You - Adventure Club Remix ~ Flight Facilities|',
     'My Pet Coelacanth ~ deadmau5|',
     'Fall Into The Sky ~ Zedd|Lucky Date|Ellie Goulding|',
     'Codec ~ Zedd|',
     'Overdrive ~ Calvin Harris|Ummet Ozcan|',
     'Midnight City ~ M83|',
     'Ghosts \'n\' Stuff - Nero Mix ~ deadmau5|Rob Swire|',
     'Under Control ~ Calvin Harris|Alesso|Hurts|',
     'Open Wide ~ Calvin Harris|Big Sean|',
     'Raise Your Weapon - Madeon Extended Remix ~ deadmau5|',
     'Outside ~ Calvin Harris|Ellie Goulding|',
     'Rude - Zedd Remix ~ Magic!|',
     'Faith ~ Calvin Harris|',
     'Ghosts \'n\' Stuff - Chuckie Remix ~ deadmau5|Rob Swire|',
     'Get Loose - Tiësto Remix ~ Showtek|Noisecontrollers|',
     'Papercut ~ Zedd|Troye Sivan|',
     'Blame ~ Calvin Harris|John Newman|',
     'Summertime Sadness [Lana Del Rey vs. Cedric Gervais] - Cedric Gervais Remix ~ Lana Del Rey|Cedric Gervais|',
     'Rope - deadmau5 mix ~ Foo Fighters|',
     'Sleepless - Radio Edit ~ CAZZETTE|The High|',
     'Lunar ~ David Guetta|Afrojack|',
     'Delirious (Boneless) ~ Steve Aoki|Chris Lake|Tujamo|Kid Ink|',
     'Face To Face ~ Daft Punk|',
     'Our Demons (feat. Aja Volkman) ~ The Glitch Mob|Aja Volkman|',
     'Some Chords ~ deadmau5|',
     'Shave It Up ~ Zedd|',
     'All of Me - (Tiësto\'s Birthday Treatment Remix) [Radio Edit] ~ John Legend|',
     'Miami Showdown ~ Digitalism|',
     'Give It Up For Me ~ Sydney Blu|',
     'Raise Your Weapon ~ deadmau5|',
     'Sofi Needs A Ladder ~ deadmau5|',
     'Satisfy ~ Nero|',
     'The Future ~ David Guetta|Afrojack|',
     'Replica - Original Mix ~ Afrojack|',
     'Raise Your Weapon - Michael Cassette Remix ~ deadmau5|',
     'Rock Steady - Original Mix ~ Julian Jordan|',
     'L\'Amour - Original Mix ~ Bingo Players|',
     'Mind of a Beast ~ The Glitch Mob|',
     'Aerodynamic (Daft Punk Remix) ~ Daft Punk|',
     'Toy Story ~ David Guetta|',
     'Ghost N Stuff - Original Mix ~ deadmau5|',
     'Sunshine ~ David Guetta|Avicii|',
     'Moar Ghosts n Stuff ~ deadmau5|',
     'Ghosts \'n\' Stuff - feat. Rob Swire ~ deadmau5|',
     'Little Bad Girl - Instrumental Edit ~ David Guetta - Ludacris - Taio Cruz|',
     'I Just Wanna F. - feat. Timbaland & Dev ~ David Guetta|Afrojack|Timbaland|DEV|',
     'The Future ~ David Guetta|Afrojack|',
     'Strobe ~ deadmau5|',
     'Five Hours ~ Deorro|',
     'Paris ~ David Guetta|',
     'Channel 42 ~ deadmau5 + Wolfgang Gartner|',
     'Sweat (Snoop Dogg vs. David Guetta) [Remix] ~ Snoop Dogg|David Guetta|',
     'Fn Pig ~ deadmau5|',
     'Glasgow ~ David Guetta|',
     'Maths - Original Mix ~ deadmau5|',
     'Give Me Everything - Afrojack Remix ~ Pitbull|Ne-Yo|Afrojack|Nayer|',
     'Roar ~ Axwell|Sebastian Ingrosso|',
     'A LIGHT THAT NEVER COMES ~ LINKIN PARK x STEVE AOKI|',
     'Hey Baby - Original Mix ~ deadmau5|Melleefresh|',
     'Tornado (Kill the Noise Remix feat. Polina) ~ Tiësto|Steve Aoki|Polina|',
     'Chasin\' - Original Extended Mix ~ Sander Van Doorn|',
     'Sex Slave - Original Mix ~ deadmau5|Melleefresh|',
     'Mammoth - Original Mix ~ Dimitri Vegas & Like Mike|Moguai|Like Mike|',
     'Avaritia ~ deadmau5|',
     'Aerodynamic Beats / Gabrielle , Forget About The World ~ Daft Punk|',
     'Autonomy ~ Zedd|',
     'Wake Me Up ~ Avicii|',
     'The Legend Of Zelda - Original Mix ~ Zedd|',
     'Roar - (From "Monsters University") [Yogi Remix] ~ Axwell|Sebastian Ingrosso|',
     'Giorgio by Moroder ~ Daft Punk|',
     'Cinema - Skrillex Remix ~ Benny Benassi|',
     'Too Close ~ Alex Clare|',
     'Touch ~ Daft Punk|Paul Williams|',
     'Get Lucky ~ Daft Punk|Pharrell Williams|Nile Rodgers|',
     'We No Speak Americano - Original Version ~ Yolanda Be Cool|DCup|',
     'Roar - Style of Eye Remix ~ Axwell|Sebastian Ingrosso|',
     'Fragments of Time ~ Daft Punk|Todd Edwards|',
     'Beam Me Up (Kill Mode) (Original Mix) ~ CAZZETTE|',
     'Around The World ~ Daft Punk|',
     'One More Time / Aerodynamic ~ Daft Punk|',
     'Greyhound ~ Swedish House Mafia|',
     'One - Original Mix ~ Swedish House Mafia|',
     'One More Time ~ Daft Punk|',
     'Your Touch ~ Blake Lewis|',
     'Fortune Days ~ The Glitch Mob|',
     'Derezzed (Remixed by The Glitch Mob) ~ Daft Punk|The Glitch Mob|',
     'The Grid (Remixed by The Crystal Method) ~ The Crystal Method|Daft Punk|',
     'Take Over Control (feat. Eva Simons) ~ Afrojack|Eva Simons|',
     'Save the World ~ Swedish House Mafia|',
     'Solar Sailer (Remixed by Pretty Lights) ~ Daft Punk|Pretty Lights|',
     'End of Line (Remixed by Boys Noize) ~ Daft Punk|Boys Noize|',
     'We Can Make The World Stop ~ The Glitch Mob|',
     'Levels ~ Avicii|',
     'We Own the Night - Original Mix ~ Tiësto|Wolfgang Gartner|Luciana|',
     'Fall (Remixed by M83 VS Big Black Delta) ~ M83 VS Big Black Delta|Daft Punk|',
     'Antidote ~ Swedish House Mafia|Knife Party|',
     'The Island (Steve Angello, AN21 & Max Vangeli Remix) ~ Pendulum|',
     'Here We Go ~ Hard Rock Sofa|Swanky Tunes|',
     'Levels - Skrillex Remix ~ Avicii|',
     'Feel Alright ~ Klaypex|',
     'Around The World / Harder Better Faster Stronger ~ Daft Punk|',
     'Mercedes ~ deadmau5|',
     'Pets ~ deadmau5|',
     'Avaritia ~ deadmau5|',
     'Coelacanth I ~ deadmau5|',
     'Ice Age - deadmau5 Remix ~ How To Destroy Angels|deadmau5|',
     'Don\'t You Worry Child (feat. John Martin) ~ Swedish House Mafia|John Martin|' ],
  'Rock': 
   [ 'Dazed And Confused ~ Led Zeppelin|',
     'Wish You Were Here - 2011 Remastered Version ~ Pink Floyd|',
     'Whole Lotta Love ~ Led Zeppelin|',
     'Welcome To The Machine - 2011 Remastered Version ~ Pink Floyd|',
     'Stairway To Heaven ~ Led Zeppelin|',
     'Immigrant Song ~ Led Zeppelin|',
     'Ramble On ~ Led Zeppelin|',
     'Babe I\'m Gonna Leave You ~ Led Zeppelin|',
     'Kashmir ~ Led Zeppelin|',
     'Trampled Under Foot ~ Led Zeppelin|',
     'Good Times Bad Times ~ Led Zeppelin|' ],
  'Soft': 
   [ 'Welcome To The Machine - 2011 Remastered Version ~ Pink Floyd|',
     'Mad World (Feat. Michael Andrews) ~ Gary Jules|Michael Andrews|',
     'Brazil ~ Geoff & Maria Muldaur|',
     'Rude ~ Magic!|',
     'Riptide ~ Vance Joy|',
     'Float On ~ Modest Mouse|',
     'Married Life ~ Michael Giacchino|',
     'Just Dropped In ~ Kenny Rogers & The First Edition|',
     'Fix You ~ Coldplay|',
     'Gravity ~ John Mayer|',
     'Circle of Life ~ Carmen Twillie|Lebo M.|',
     'Escape (The Pina Colada Song) ~ Rupert Holmes|',
     'Hooked on a Feeling ~ Blue Swede|',
     'Lava ~ Kuana Torres Kahele|Napua Greig|James Ford Murphy|',
     'The Man in Me ~ Bob Dylan|',
     'Fooled Around And Fell In Love ~ Elvin Bishop|',
     'Hotel California (Spanish Mix) ~ Gipsy Kings|',
     'I\'m Not In Love ~ 10cc|',
     'Ecstasy ~ Calvin Harris|Hurts|',
     'Say Something ~ A Great Big World|',
     'Thinking Out Loud ~ Ed Sheeran|',
     'Rather Be (feat. Jess Glynne) ~ Clean Bandit|Jess Glynne|',
     'Tumbling Tumbleweeds ~ Sons of the Pioneers|',
     'Sail ~ AWOLNATION|',
     'Stay ~ Rihanna|Mikky Ekko|',
     'Time ~ Hans Zimmer|',
     'Dream Is Collapsing ~ Hans Zimmer|',
     '503 ~ Hans Zimmer|Joshua Bell|',
     'I\'ll Be Waiting (Kabhi Jo Baadal Barse) Arjun Feat.Arijit Singh - Full Video Song (HD) ~ |',
     'Every Morning ~ Sugar Ray|',
     'We Belong Together ~ Randy Newman|',
     'You\'ve Got A Friend In Me ~ Randy Newman|',
     'You\'ve Got A Friend In Me (Hay Un Amigo en Mi) ~ Gipsy Kings|',
     'Stay With Me ~ Sam Smith|',
     'human ~ Christina Perri|',
     'Dead Flowers - Remastered 2009 ~ The Rolling Stones|',
     'Let My Love Open the Door ~ Luminate|',
     'Let It Go ~ Idina Menzel|',
     'Demons ~ Imagine Dragons|',
     'Hotel California ~ Eagles|',
     'Can You Feel the Love Tonight ~ Joseph Williams|Sally Dworsky|Nathan Lane|Ernie Sabella|Kristle Edwards|',
     'I Will Wait ~ Mumford & Sons|',
     'Little Talks ~ Of Monsters and Men|',
     'When She Loved Me ~ Sarah McLachlan|',
     'A Princess ~ Javier Navarrete|',
     'Stay ~ Hans Zimmer|',
     'Le Festin ~ Camille|',
     'Happy - From "Despicable Me 2" ~ Pharrell Williams|',
     'Need You Now ~ Lady Antebellum|',
     'Locked Away ~ R. City|Adam Levine|',
     'A Thousand Years ~ Christina Perri|',
     'Route 66 ~ John Mayer|',
     'Sh-Boom ~ The Chords|',
     'Real Gone ~ Sheryl Crow|',
     'Life Is A Highway - From "Cars" ~ Rascal Flatts|',
     'Hakuna Matata ~ Nathan Lane|Ernie Sabella|Jason Weaver|Joseph Williams|',
     'Love Is an Open Door ~ Kristen Bell|Santino Fontana|',
     'For the First Time in Forever ~ Kristen Bell|Idina Menzel|',
     'The Middle ~ Jimmy Eat World|',
     'Can You Feel The Love Tonight ~ Elton John|',
     'Do You Want to Build a Snowman? ~ Kristen Bell|Agatha Lee Monn|Katie Lopez|',
     'Pompeii ~ Bastille|',
     'For the First Time in Forever (Reprise) ~ Kristen Bell|Idina Menzel|',
     'Three Little Birds ~ Bob Marley & The Wailers|',
     'Treasure ~ Bruno Mars|',
     'First Day ~ Thomas Newman|',
     'Count On Me ~ Bruno Mars|',
     'Rude (Acoustic) ~ Magic!|' ],
  'Popular': 
   [ 'Can\'t Feel My Face ~ The Weeknd|',
     'Shut Up and Dance ~ Walk the Moon|',
     'Want To Want Me ~ Jason Derulo|',
     'Worth It ~ Fifth Harmony|Kid Ink|',
     'Somebody ~ Natalie La Rose|Jeremih|',
     'Earned It (Fifty Shades Of Grey) - From The "Fifty Shades Of Grey" Soundtrack ~ The Weeknd|',
     'Trap Queen ~ Fetty Wap|',
     'See You Again (feat. Charlie Puth) ~ Wiz Khalifa|Charlie Puth|',
     'Fun ~ Pitbull|Chris Brown|',
     'Do It Again ~ Pia Mia|Chris Brown|Tyga|',
     'The Hills ~ The Weeknd|',
     'Time of Our Lives ~ Pitbull|Ne-Yo|',
     'Hey Mama (feat. Nicki Minaj, Bebe Rexha & Afrojack) ~ David Guetta|Bebe Rexha|Nicki Minaj|Afrojack|',
     'Uptown Funk ~ Mark Ronson|Bruno Mars|',
     'FourFiveSeconds ~ Rihanna|Kanye West|Paul McCartney|',
     'Sugar ~ Maroon 5|',
     'Love Me Like You Do - From "Fifty Shades Of Grey" ~ Ellie Goulding|',
     'Surrender - Pierce Fulton Remix ~ Cash Cash|',
     'Chandelier ~ Sia|',
     'Runaway (U & I) ~ Galantis|',
     'Dangerous (feat. Sam Martin) ~ David Guetta|Sam Martin|',
     'Lights ~ Ellie Goulding|',
     'Moves Like Jagger - Studio Recording From The Voice Performance ~ Maroon 5|Christina Aguilera|',
     'I\'m Gonna Show You Crazy ~ Bebe Rexha|',
     'Break The Rules ~ Charli XCX|',
     'La La La ~ Naughty Boy|Sam Smith|',
     'Bring Me To Life ~ Evanescence|',
     'Crave You ~ Flight Facilities|',
     'Sing ~ Ed Sheeran|',
     'We Are Young (feat. Janelle Monáe) - feat. Janelle Monae ~ Fun.|Janelle Monáe|',
     'Muevelo - feat. Wisin ~ Sofia Reyes|',
     'Suit & Tie featuring JAY Z ~ Justin Timberlake|JAY Z|',
     'Stolen Dance ~ Milky Chance|',
     'Superheroes ~ The Script|',
     'Dare (La la la) ~ Shakira|',
     'Classic ~ MKTO|',
     'SexyBack ~ Justin Timberlake|Timbaland|',
     'Bon, Bon ~ Pitbull|',
     'Problem ~ Ariana Grande|Iggy Azalea|',
     'Stay The Night - Featuring Hayley Williams Of Paramore ~ Zedd|Hayley Williams|',
     'The Way ~ Ariana Grande|Mac Miller|',
     'The Middle ~ Jimmy Eat World|',
     'It Ends Tonight ~ The All-American Rejects|',
     'Radioactive ~ Imagine Dragons|',
     'Can\'t Remember to Forget You ~ Shakira|Rihanna|',
     'Counting Stars ~ OneRepublic|',
     'Sail - Live from Spotify Sxsw 2014 ~ Vitamin String Quartet|',
     'Give Me Everything ~ Pitbull|Ne-Yo|Afrojack|Nayer|',
     'Hips Don\'t Lie ~ Shakira|Wyclef Jean|',
     'The Monster ~ Eminem|Rihanna|',
     'Sweet Nothing ~ Calvin Harris|Florence Welch|',
     'It\'s Time ~ Imagine Dragons|',
     'Need You Now ~ Lady Antebellum|',
     'Summertime Sadness [Lana Del Rey vs. Cedric Gervais] - Cedric Gervais Remix ~ Lana Del Rey|Cedric Gervais|',
     'I Need Your Love ~ Calvin Harris|Ellie Goulding|',
     'We No Speak Americano - Original Version ~ Yolanda Be Cool|DCup|',
     'Don\'t Stop the Party ~ Pitbull|TJR|',
     'Summertime Sadness ~ Lana Del Rey|',
     'Exotic ~ Priyanka Chopra|Pitbull|',
     'All Night ~ Icona Pop|',
     'Feel This Moment ~ Pitbull|Christina Aguilera|',
     'Yeah! ~ Usher|Lil Jon|Ludacris|',
     'All of Me ~ John Legend|',
     'Heart Attack ~ Demi Lovato|',
     'Latch ~ Disclosure|Sam Smith|',
     '2 Reasons (feat. T.I.) ~ Trey Songz|T.I.|',
     'It\'s Time ~ Imagine Dragons|',
     'Behind Blue Eyes ~ Limp Bizkit|',
     'Secrets ~ OneRepublic|',
     'Helena Beat ~ Foster The People|',
     'Paradise ~ Coldplay|',
     'Bass Down Low ~ DEV|The Cataracs|',
     'The Choice Is Yours (Revisited) ~ Black Sheep|',
     'Thrift Shop - feat. Wanz ~ Macklemore & Ryan Lewis|',
     'Good Time ~ Carly Rae Jepsen, Owl City|',
     'Pumped up Kicks ~ Foster The People|',
     'Sexy And I Know It ~ LMFAO|',
     'Party Rock Anthem ~ LMFAO|Lauren Bennett|GoonRock|',
     'Stereo Hearts - feat. Adam Levine ~ Gym Class Heroes|',
     'She Will Be Loved ~ Maroon 5|',
     'Every Teardrop Is A Waterfall ~ Coldplay|',
     'Viva La Vida ~ Coldplay|',
     'Club Can\'t Handle Me - feat. David Guetta ~ Flo Rida|',
     'Sexy Bitch (feat. Akon) - Featuring Akon;explicit ~ David Guetta|Akon|',
     'We No Speak Americano - Myd Remix ~ Yolanda Be Cool|DCup|',
     'The Other Side ~ Jason Derulo|',
     'Raging Fire ~ Phillip Phillips|',
     'Am I Wrong ~ Nico & Vinz|' ],
  'Random Access Memories': 
   [ 'Give Life Back to Music ~ Daft Punk|',
     'The Game of Love ~ Daft Punk|',
     'Within ~ Daft Punk|',
     'Instant Crush ~ Daft Punk|Julian Casablancas|',
     'Giorgio by Moroder ~ Daft Punk|',
     'Get Lucky ~ Daft Punk|Pharrell Williams|Nile Rodgers|',
     'Touch ~ Daft Punk|Paul Williams|',
     'Doin\' it Right ~ Daft Punk|Panda Bear|',
     'Fragments of Time ~ Daft Punk|Todd Edwards|',
     'Lose Yourself to Dance ~ Daft Punk|Pharrell Williams|',
     'Beyond ~ Daft Punk|',
     'Motherboard ~ Daft Punk|',
     'Contact ~ Daft Punk|' ],
  'Musica Buena': 
   [ 'No Hay Nadie Como Tú ~ Calle 13|Café Tacvba|',
     'Bonito ~ McMaw Band|',
     'Muerte En Hawaii ~ Calle 13|',
     'Atrévete Te Te ~ Calle 13|',
     'Baile De Los Pobres ~ Calle 13|',
     'Grita ~ Jarabe De Palo|',
     'Niña Bonita ~ Chino & Nacho|',
     'Bebé Bonita ~ Chino & Nacho|Jay Sean|',
     'Tu Angelito ~ Chino & Nacho|',
     'El Poeta ~ Chino & Nacho|',
     'Lo Que No Sabes Tú ~ Chino & Nacho|Baroni|El Potro Alvarez|',
     'Buscándola ~ Maná|',
     'Ando Buscandola ~ Cideli|',
     'Danza Kuduro ~ Don Omar|Lucenzo|',
     'Puerto Presente (feat. Fito Cabrales) ~ Macaco/Fito Carbrales|Fito Cabrales|',
     'Corazón Sin Cara ~ Prince Royce|',
     'Estoy Enamorado ~ Wisin & Yandel|',
     'La Calle - feat. Juanes ~ Juan Luis Guerra|Juanes|',
     'En El Muelle De San Blas ~ Maná|',
     'El Amor ~ Tito "El Bambino"|',
     'Me Estas Tentando ~ Wisin & Yandel|',
     'Volverte A Ver ~ Juanes|',
     'Un Día Normal ~ Juanes|',
     'Buscandote - Original Mix ~ Charly Rodriguez|',
     'Se Vuelve Loca ~ Juan Magan|',
     'La Camisa Negra ~ Juanes|',
     'Fotografía ~ Nelly Furtado|Juanes|',
     'Soy ~ Gipsy Kings|',
     'Volare ~ Gipsy Kings|',
     'Vamos A Bailar ~ Gipsy Kings|',
     'A Dios Le Pido ~ Juanes|',
     'Lovumba ~ Daddy Yankee|',
     'Hasta Que Salga El Sol ~ Don Omar|',
     '1977 ~ Ana Tijoux|',
     'Lento ~ Julieta Venegas|',
     'Ven Y Critícame ~ Calle 13|',
     'Calma Pueblo ~ Calle 13|Omar Rodriguez|',
     'John, El Esquizofrénico ~ Calle 13|',
     'Te Llevaré Al Cielo ~ Grupo M.A.M|',
     'Cuando los ángeles lloran ~ Maná|',
     'Latinoamérica ~ Calle 13|Totó La Momposina|Susana Baca|Maria Rita|',
     'Vivir Mi Vida ~ Marc Anthony|',
     'Oye Como Va ~ Santana|',
     'Dale Asi (feat. Mr. Fox) ~ Major Lazer|' ],
  'Liked from Radio': 
   [ 'Love Lockdown ~ Kanye West|',
     'All Of The Lights ~ Kanye West|',
     'Love The Way You Lie ~ Eminem|Rihanna|',
     'Moar Ghosts \'n\' Stuff ~ deadmau5|',
     'The Sound Of Silence ~ Simon & Garfunkel|Art Garfunkel|Paul Simon|',
     'Day \'N\' Nite - Original ~ Kid Cudi|',
     'Stronger ~ Kanye West|',
     '\'Till I Collapse ~ Eminem|Nate Dogg|',
     'POWER ~ Kanye West|',
     'Homecoming ~ Kanye West|Chris Martin|',
     'Strobe - Radio Edit ~ deadmau5|',
     'Like A G6 ~ Far East Movement|The Cataracs|DEV|',
     'Where Is The Love? ~ The Black Eyed Peas|',
     'Sexy Bitch (feat. Akon) - Featuring Akon;explicit ~ David Guetta|',
     'I Gotta Feeling ~ The Black Eyed Peas|',
     'Lose Yourself - Soundtrack Version ~ Eminem|',
     'Stan ~ Eminem|Dido|',
     'Love Lockdown ~ Kanye West|',
     'Gold Digger ~ Kanye West|Jamie Foxx|',
     'Hell Of A Life ~ Kanye West|',
     'Harder Better Faster Stronger ~ Daft Punk|',
     'Wake Me Up When September Ends ~ Green Day|',
     'Numb ~ Linkin Park|',
     'Loca People (What the F**k!") - Radio Edit ~ Sak Noel|',
     'The Real Slim Shady ~ Eminem|',
     'Ghosts \'n\' Stuff - feat. Rob Swire ~ deadmau5|',
     'Pursuit Of Happiness (nightmare) ~ Kid Cudi|MGMT|Ratatat|',
     'Stan ~ Eminem|Dido|',
     'One - Radio Edit ~ Swedish House Mafia|',
     'Numb/Encore ~ JAY Z|Linkin Park|',
     'Hell Of A Life ~ Kanye West|',
     'Stan ~ Eminem|Dido|',
     'Not Afraid ~ Eminem|',
     'Loca People (What the F**k!") - Radio Edit ~ Sak Noel|',
     'Some Chords ~ deadmau5|',
     'Raise Your Weapon - Original Mix ~ deadmau5|',
     'Stronger ~ Kanye West|',
     '\'Till I Collapse ~ Eminem|Nate Dogg|',
     'Strobe ~ deadmau5|',
     'Strobe ~ deadmau5|',
     'E.T. - feat. Kanye West ~ Katy Perry|',
     'Stronger ~ Kanye West|',
     'All Of The Lights ~ Kanye West|',
     'Good Morning ~ Kanye West|',
     'Heartless ~ Kanye West|',
     'The Time (Dirty Bit) ~ The Black Eyed Peas|',
     'Erase Me - Main ~ Kid Cudi|Kanye West|',
     'Mercy ~ Kanye West|Big Sean|Pusha T|2 Chainz|',
     'All Of The Lights ~ Kanye West|',
     'Antidote ~ Swedish House Mafia|Knife Party|',
     'I Wonder ~ Kanye West|',
     'Good Life ~ Kanye West|T-Pain|',
     'Hey Mama ~ Kanye West|',
     'Daydreamin\' - feat. Jill Scott ~ Lupe Fiasco|',
     'All Of The Lights (Interlude) ~ Kanye West|',
     'Pursuit Of Happiness (nightmare) ~ Kid Cudi|MGMT|Ratatat|',
     'POWER ~ Kanye West|',
     'Amazing ~ Kanye West|Jeezy|',
     'Jesus Walks ~ Kanye West|',
     'Greyhound ~ Swedish House Mafia|',
     'Love Lockdown ~ Kanye West|',
     'Love The Way You Lie ~ Eminem|Rihanna|',
     'Erase Me - Main ~ Kid Cudi|Kanye West|',
     'Daydreamin\' - feat. Jill Scott ~ Lupe Fiasco|',
     'Gorgeous ~ Kanye West|Kid Cudi|Raekwon|',
     'All Of The Lights ~ Kanye West|',
     'All Falls Down ~ Kanye West|Syleena Johnson|',
     'I Wonder ~ Kanye West|',
     'Monster ~ Kanye West|JAY Z|Rick Ross|Nicki Minaj|Bon Iver|',
     'Hey Mama ~ Kanye West|',
     'Erase Me - Main ~ Kid Cudi|Kanye West|',
     'Behind Blue Eyes ~ Limp Bizkit|',
     'Stronger ~ Kanye West|',
     'Greyhound ~ Swedish House Mafia|',
     'Some Chords ~ deadmau5|',
     'Save the World ~ Swedish House Mafia|',
     'Can\'t Tell Me Nothing ~ Kanye West|',
     'POWER ~ Kanye West|',
     'Derezzed ~ Daft Punk|',
     'Pursuit Of Happiness (nightmare) ~ Kid Cudi|MGMT|Ratatat|',
     'Around The World ~ Daft Punk|',
     'Cookie Jar - feat. The-Dream ~ Gym Class Heroes|',
     'Daydreamin\' - feat. Jill Scott ~ Lupe Fiasco|',
     'Around The World ~ Daft Punk|',
     'Around The World ~ Daft Punk|' ],
  'Badass Classical': 
   [ 'Carmina Burana (Cantiones Profanae), Fortuna Imperatrix Mundi: I. O Fortuna - II. Fortuna Plango Vulnera ~ South German Philharmonic Orchestra|',
     'Piano Trio No. 2 In E Flat Major, Op. 100, D. 929: II. Andante Con Moto ~ Stuttgart Piano Trio|Franz Schubert|',
     'Requiem In D Minor, K 626 - 1. Introitus: Requiem Aeternam ~ Wolfgang Amadeus Mozart|',
     'Messa da Requiem, Sequenza:: Dies irae ~ Cheryl Studer|Dolora Zajick|Luciano Pavarotti|Samuel Ramey|Coro e Orchestra del Teatro alla Scala, Milano|Riccardo Muti|',
     'Requiem in D Minor, K. 626: Lacrimosa ~ Wolfgang Amadeus Mozart|The Cavendish Orchestra|The Cavendish Voices|Terry Cavendish|',
     'Serenata D.957 - Schubert ~ The Royal Schubert Orchestra|',
     'Mozart : Requiem in D minor K626 : III Dies irae ~ Nikolaus Harnoncourt|Concentus Musicus Wien|Vienna State Opera Chorus|',
     'Romeo and Juliet, Op.64, Act I: Dance of the Knights ~ André Previn|',
     'Night On Bald Mountain ~ Prague Symphony Orchestra|Modest Mussorgsky|Jiri Belohlavek|',
     'Lohengrin Prelude to Act III ~ Richard Wagner|Various Artists|',
     'Symphony No. 4 in A Major, Op. 90, "Italian": IV. Saltarello: Presto ~ Bamberg Symphony Orchestra|',
     'Symphony No. 8 in B Minor, D.759 "Unfinished" (1996 Digital Remaster): I. Allegro moderato ~ Herbert von Karajan|',
     'Swan Lake - Scene ~ Pyotr Ilyich Tchaikovsky|',
     'The Valkyrie: Ride Of The Valkyries ~ London Philharmonic Orchestra|David Parry|',
     'La Donna È Mobile ~ Giuseppe Verdi|',
     'Por Ti Volare (Con Te Partiro) - Spanish Version ~ Andrea Bocelli|',
     'Symphony No. 7 in A Major, Op. 92: II. Allegretto ~ Ludwig van Beethoven|London Symphony Orchestra|',
     'Symphony No. 9 in E Minor, Op. 95 - "From the New World": IV. Allegro con fuoco ~ New York Stadium Symphony Orchestra|Leonard Bernstein|',
     'Overture (Suite) No. 3 in D Major, BWV 1068: II: Air on a G String ~ Johann Sebastian Bach|The Cavendish Orchestra|Terry Cavendish|',
     'Adagio In G Minor For Strings And Organ (After T. Albinoni) ~ London Philharmonic Orchestra|David Parry|',
     'Pictures at an Exhibition: The Great Gates of Kiev ~ London Festival Orchestra|Alfred Scholz|',
     'Prince Igor, Polovtsian Dances: I. Introduction - Andantino ~ Alexander Borodin|Tbilisi Symphony Orchestra|',
     'Piano Sonata No. 11 In A Major, K. 331: III. Rondo Alla Turca: Allegretto ~ Wolfgang Amadeus Mozart|',
     'Piano Concerto No. 21 In C Major, "Elvira Madigan": II. Andante ~ Wolfgang Amadeus Mozart|',
     'IV. Theme With Variations ~ Franz Schubert|',
     'Impromptus, D. 899 (Op. 90): Impromptu No. 3 in G-Flat Major: Andante ~ Murray Perahia|',
     'Clair de Lune - Debussy ~ Exam Study Classical Music Orchestra|',
     'Hungarian Rhapsody No. 2 in C-Sharp Minor, S.244/2 ~ Franz Liszt|Vladimir Mishchuk|',
     'Grandes études de Paganini, S.141: Étude No. 3 in G-Sharp Minor "La Campanella" ~ Franz Liszt|Vladimir Mishchuk|',
     'Rhapsody In Blue ~ George Gershwin|',
     '12 Études, Op. 25: No. 12 in C Minor, "Ocean": Allegro molto con fuoco ~ Frédéric Chopin|Nikita Magaloff|',
     'Chopin: Etude No.1 In C Major Op.10-1 ~ Zbigniew Raubo|',
     'Prelude No. 2 in C-Sharp Minor, Op. 3: Op. 3 No. 2 in C sharp minor ~ Peter Katin|',
     'Toccata and Fugue in D Minor for Organ, BWV 565 ~ Johann Sebastian Bach|Klemens Schnorr|',
     'Cello Suite No. 1 in G Major, BWV 1007: Prelude ~ Johann Sebastian Bach|Tristan Mark|',
     'Gymnopédie No. 1 ~ Finghin Collins|',
     'Symphony No. 9 in E Minor, Op. 95 - "From the New World": I. Adagio. Allegro molto ~ New York Stadium Symphony Orchestra|Leonard Bernstein|',
     'Symphony No. 9 in E Minor, Op. 95 - "From the New World": II. Largo ~ New York Stadium Symphony Orchestra|Leonard Bernstein|',
     'Symphony No. 9 in E Minor, Op. 95 - "From the New World": III. Scherzo. Molto vivace ~ New York Stadium Symphony Orchestra|Leonard Bernstein|',
     'Nocturne in F-Minor Op. 55, No. 1 ~ Frédéric Chopin|Vladmir Feltsman|',
     'Sonata No. 2 in b flat minor for Piano, Op. 35, Grave \'Funeral March\' ~ Frédéric Chopin|',
     'Sonata No. 2 in B Minor for Piano, Op. 35: Funeral March ~ Henrik Måwe|',
     'Brandenburg Concerto No.3 In G Major, BWV 1048: I: Allegro ~ Johann Sebastian Bach|The Cavendish Orchestra|Terry Cavendish|',
     'Brandenburg Concerto No. 1 in F Major, BWV 1046: II. Adagio - Allegro ~ Johann Sebastian Bach|Leningrad Chamber Orchestra|Vitaliy Buyanovskiy|Vladimir Shalyt|Vladimir Kurlin|Lazar Gozman|',
     'No3 A- Canones diversi ~ Shinji Ishihara|',
     'No2 Canon perpetuus ~ Shinji Ishihara|',
     'Traumerei Op.15/7 (Dreaming from Scenes From Childhood) ~ Robert Schumann|Various Artists|',
     'The Musical Offering: Ricercar a 3 ~ Camerata Kilkenny|',
     'Oboe Concerto in A minor, RV 461: I. Allegro ~ Antonio Vivaldi|Leningrad Chamber Orchestra|Vladimir Kurlin|Lazar Gozman|',
     'Nocturne No. 2 in E flat Major, Op. 9,2 ~ Frédéric Chopin|',
     'Matthäus Passion, BWV 244: Chori, "Kommt, ihr Töchter, helft mir klagen" ~ Johann Sebastian Bach|Ton Koopman|Boys Choir Of Sacraments-Church Breda|',
     'Symphony No. 40 in G Minor, KV. 550: I: Molto allegro ~ Wolfgang Amadeus Mozart|The Cavendish Orchestra|Terry Cavendish|',
     'St. Matthew Passion, BWV 244: No. 39 Arie (Alt): Erbarme dich, mein Gott ~ Johann Sebastian Bach|Istvan Gati|Peter Koves|Agnes Mester|Jozsef Mukk|Judit Nemeth|Janos Remenyi|Ibolya Verebics|Hungarian Festival Chorus|Hungarian Radio Children\'s Choir|Hungarian State Symphony Orchestra|Géza Oberfrank|',
     'Waltz No. 7 in C-Sharp Minor, Op. 64/2 ~ Elfrun Gabriel|',
     'Turandot, Act 3: Nessun Dorma ~ Luciano Pavarotti|',
     'Molossus ~ Hans Zimmer|James Newton Howard|',
     'Sarasate : Zigeunerweisen Op.20 ~ Charlie Siem|' ],
  'M50X Blaster': 
   [ 'Change ~ Flume|',
     'What\'s The Difference ~ Dr. Dre|Eminem|Xzibit|',
     'Seeya ~ deadmau5|Colleen D\'agostino|',
     'Get Lucky ~ Daft Punk|Pharrell Williams|Nile Rodgers|',
     'My Head Is A Jungle - Extended Vocal Mix ~ Wankelmut|Emma Louise|',
     'Sleeping With A Friend - The Chainsmokers Radio Remix ~ Neon Trees|',
     'Strong ~ Arno Cost & Norman Doray|Arno Cost|Norman Doray|',
     'Fade Into Darkness - Vocal Club Mix ~ Avicii|',
     'Summertime Sadness [Lana Del Rey vs. Cedric Gervais] - Cedric Gervais Remix ~ Lana Del Rey|Cedric Gervais|',
     'Crave You - Adventure Club Remix ~ Flight Facilities|',
     'Touch ~ Daft Punk|Paul Williams|',
     'What Goes Around.../...Comes Around Interlude ~ Justin Timberlake|',
     'Tear The Roof Up ~ Alesso|',
     'Pressure - Alesso Remix ~ Nadia Ali|Starkillers|Alex Kenji|',
     'Infra Turbo Pigcart Racer ~ deadmau5|',
     'I Can\'t Stop ~ Flux Pavilion|',
     'Avaritia ~ deadmau5|',
     'Miami 2 Ibiza ~ Swedish House Mafia|Tinie Tempah|',
     'Don\'t You Worry Child (Radio Edit) [feat. John Martin] ~ Swedish House Mafia|John Martin|',
     'Blue Jeans - RAC Mix ~ Lana Del Rey|',
     'Rock Steady - Original Mix ~ Julian Jordan|',
     'SexyBack ~ Justin Timberlake|Timbaland|',
     'Midnight City ~ M83|',
     'You Know You Like It (Dj Snake Remix) ~ AlunaGeorge|',
     'West Coast ~ The Neighbourhood|',
     'Animals ~ Martin Garrix|',
     'Look Right Through - MK Vocal Edit ~ Storm Queen|',
     'Such Great Heights ~ The Postal Service|',
     'On The Run - 2011 Remastered Version ~ Pink Floyd|',
     'Take, Take, Take ~ The White Stripes|',
     'Fall Into The Sky ~ Zedd|Lucky Date|Ellie Goulding|',
     'Can\'t Stop Playing - Oliver Heldens & Gregor Salto Remix Edit ~ DR. KUCHO!|Gregor Salto|',
     'We Found Love (feat. Calvin Harris) [Extended Mix] ~ Rihanna|',
     'Amber Button ~ Isan|',
     'Surface ~ Aero Chord|' ],
  'Programming (EDM)': 
   [ 'Melody - Original Mix ~ Oliver Heldens|',
     'Take Me Home (feat. Bebe Rexha) ~ Cash Cash|Bebe Rexha|',
     'Miami 2 Ibiza ~ Swedish House Mafia|Tinie Tempah|',
     'Antidote ~ Swedish House Mafia|Knife Party|',
     'One (Your Name) [feat. Pharrell] [Radio Edit] ~ Swedish House Mafia|Pharrell Williams|',
     'Save the World ~ Swedish House Mafia|',
     'Fortune Days ~ The Glitch Mob|',
     'We Can Make The World Stop ~ The Glitch Mob|',
     'Lights - Bassnectar Remix ~ Ellie Goulding|',
     'Breathe (The Glitch Mob Remix) ~ The Prodigy|',
     'D.A.N.C.E. [Benny Blanco Remix Feat Spank Rock & Mos Def] ~ Justice|',
     'The Game Has Changed ~ Daft Punk|',
     'Lights - Bassnectar Remix ~ Ellie Goulding|',
     'Fresh Scream - Original Mix ~ Al Bizzare|',
     'Prituri Se Planinata - NiT GriT Remix ~ Nit Grit|Stellamara|',
     'Ghosts \'n\' Stuff - Nero Remix;feat. Rob Swire ~ deadmau5|',
     'Resurrection - Axwell\'s Recut Radio Edit ~ Michael Calfan|',
     'Resurrection (Axwell mix) / Coldplay ˆ Paradise ~ Michael Calfan|',
     'Raise Your Head / Sandro Silva & Quintino ˆ Epic ~ Alesso|',
     'If I Lose Myself - Alesso vs OneRepublic ~ OneRepublic|Alesso|',
     'Years - Radio Edit ~ Alesso|Matthew Koma|',
     'Ching Choing - Radio Edit ~ Michael Calfan|Kaye Styles|',
     'White Noise ~ Disclosure|AlunaGeorge|',
     'Silenced By The Night - Alesso Remix ~ Keane|Alesso|',
     'Nillionaire ~ Alesso|',
     'Clash - Original Mix ~ Alesso|',
     'Let Your Mind Go - Original Mix ~ Michael Calfan|John Dahlbäck|Andy P|',
     'Think Its Time - Original Mix ~ Alesso|',
     'Groovy Baby - Hard Rock Sofa Remix ~ Plastik Funk|Tune Brothers|',
     'Sweet Dreams (Cazzette Meets at Night Mix) ~ Avicii|',
     'Sweet Dreams - Original Mix ~ Stereo Express|',
     'Paradise - Tiësto Remix ~ Coldplay|',
     'Fade Into Darkness - Vocal Club Mix ~ Avicii|',
     'Swedish Beauty ~ An21|Max Vangeli|',
     'Ammo ~ D-Wayne|',
     'Blue Jeans - RAC Mix ~ Lana Del Rey|',
     'On The Road (Master Intro) ~ CAZZETTE|',
     'Animal Rights ~ deadmau5 + Wolfgang Gartner|',
     'Propane Nightmares ~ Pendulum|',
     'All I Know ~ Fenech-Soler|',
     'Blue Jeans - Gesaffelstein Remix ~ Lana Del Rey|',
     'Lessons In Love ~ Kaskade|Neon Trees|',
     'What Happens In Vegas - feat. Gregor Salto [Radio Edit] ~ Chuckie|',
     'When I Dip - Original Mix ~ Bingo Players|',
     'I Found You - Steve Pitron & Max Sanna Club Mix ~ The Wanted|',
     'Ivory - The Bloody Beetroots Remix ~ Congorock|',
     'Kick Out The Epic Motherf**ker ~ Dada Life|',
     'Feed the Dada - Radio Edit ~ Dada Life|',
     'Warp 1.9 (feat. Steve Aoki) ~ The Bloody Beetroots|',
     'Cornelius (Radio Oi!) ~ The Bloody Beetroots|',
     'Right This Second ~ deadmau5|',
     'Global Concepts - Radio Edit (Clean) ~ Robert DeLong|',
     'We Own the Night - Original Mix ~ Tiësto|Wolfgang Gartner|Luciana|',
     'Hook Shot ~ Wolfgang Gartner|',
     'Maximal Crazy (Radio Edit) ~ Tiësto|',
     'Work Hard, Play Hard (Radio Mix) ~ Tiësto|',
     'Doomsday ~ Nero|',
     'Got 2 Know ~ Flux Pavilion|',
     'In My Mind - feat. Georgi Kay [Axwell Mix] ~ Ivan Gough|Feenixpawl|',
     'Reload - Vocal Version / Radio Edit ~ Sebastian Ingrosso|Tommy Trash|John Martin|',
     'Trash - Original ~ The Whip|',
     'Sacrilege - Tommie Sunshine & Live City Remix ~ Yeah Yeah Yeahs|',
     'Pressure - Alesso Remix ~ Nadia Ali|Starkillers|Alex Kenji|',
     'Changed The Way You Kiss Me - Chuckie Edit ~ Example|',
     'Take You Higher - Radio Edit ~ Goodwill|Hook N Sling|',
     'Summertime Sadness [Lana Del Rey vs. Cedric Gervais] - Cedric Gervais Remix ~ Lana Del Rey|Cedric Gervais|',
     'Get Loose - Tiësto Remix ~ Showtek|Noisecontrollers|',
     'Believe It - Cazzette\'s Androids Sound Hot Remix ~ Spencer & Hill|Nadia Ali|',
     'Spread The Love - Digital Lab Remix ~ Pedro Henriques|Guiseppe Viola|',
     'Intro - XX Booty Mix ~ Sander Van Doorn|',
     'The Final Countdown - Original mix ~ Marc MacRowland|',
     'Close To Me ~ Benny Benassi|Gary Go|',
     'Must Be The Love - Shogun Radio Edit ~ Arty|Nadia Ali|BT|',
     'Cinema - Extended ~ Benny Benassi|Gary Go|',
     'Locked Out Of Heaven - Sultan and Ned Shepard Remix ~ Bruno Mars|',
     'RAW - Original Mix ~ Fedde Le Grand|',
     'Sonnentanz - Original Version ~ Klangkarussell|',
     'Rage-Aholics - Original Mix ~ Kenneth G|',
     'Just Some Loops - Original Mix ~ Martin Garrix|TV Noise|',
     'Buming Boombox - Original Mix ~ Rune RK|',
     'Are You Burning ~ Rune RK|Engelina|',
     'Carnival - Official Radio Edit ~ Phoenix|Milan|',
     'Replica - Original Mix ~ Afrojack|',
     'Rock Steady - Original Mix ~ Julian Jordan|',
     'Under Control ~ Calvin Harris|Alesso|Hurts|',
     'Alive At Night - Original Mix ~ Junior Sanchez|Ineabell|',
     'Wicked Games ~ Parra for Cuva|Anna Naklab|',
     'Magnet - Original Mix ~ Hook N Sling|Chris Willis|',
     'Young And Beautiful [Lana Del Rey vs. Cedric Gervais] - Cedric Gervais Remix Radio Edit ~ Lana Del Rey|Cedric Gervais|',
     'Heartbreaker feat. John Legend (Wolfgang Gartner Remix) ~ MSTRKRFT|John Legend|Wolfgang Gartner|',
     'Who We Are - Original Mix ~ David Solano|Angelika Vee|',
     'Made to Love - Benny Benassi Remix ~ John Legend|',
     'Revolution - Vocal Mix ~ R3hab|NERVO|Ummet Ozcan|',
     'Turn It Around - MK Dub ~ Sub Focus|Kele|',
     'Invincible - Radio Edit ~ Borgeous|',
     'A Place In The Sun - Original Mix ~ Alex Lamb & DavidAze|',
     'Not Taking This No More - Yves Larock Remix ~ NERVO|Ivan Gough|Beverley Knight|',
     'Lowdown - Original Mix ~ Vicetone|',
     'Feeling Good - Bassnectar Remix ~ Nina Simone|',
     'Turn Me On (Michael Calfan Remix) ~ David Guetta|',
     'Red Lights - twoloud Remix ~ Tiësto|',
     'Move To The Rhythm - Original Mix ~ Tiësto|Nari & Milani|Delayers|',
     'Kamikaze - Original Mix ~ LA Riots|Polina|',
     'Zebra ~ Solee|',
     'Looking for Something - Radio Edit ~ Bad Boy Bill & DJ Bam Bam feat. Miss Palmer|',
     'Hypnotica - Original Mix ~ Landis|',
     'Dangerous Thoughts - Original Mix ~ S-Man|',
     'The Buzz - Original Mix Edit ~ New World Sound|Timmy Trumpet|',
     'People Of The Night - Dimitri Vangelis & Wyman Remix ~ An21|Max Vangeli|Tiësto|Lover Lover|',
     'Piranha - Original Mix ~ Wolfgang Gartner|',
     'Endorphins - Tommy Trash Remix ~ Sub Focus|Alex Clare|',
     'Turn Back Time ~ Sub Focus|',
     'Come On Now (Set It Off) - Radio Edit ~ Tube & Berger|Juliet Sikora|',
     'One Day They\'ll Know (ODESZA Remix) ~ Pretty Lights|',
     'Sticky Fingers ~ Above & Beyond|Alex Vargas|',
     'All These Roads (feat. Zella Day and Sam Martin) - FIXYN Remix ~ Sultan + Shepard |',
     'Lunatic - Original Mix ~ Mercer|DJ Snake|',
     'Parade - Original Mix ~ Aevion|',
     'My Head Is A Jungle - Extended Vocal Mix ~ Wankelmut|Emma Louise|',
     'Payback ~ Dimitri Vangelis & Wyman|Steve Angello|',
     'Burnt Sun - Radio Edit ~ Bryan Cox|Sergio Pardo|',
     'Wildfire - Radio Edit ~ Borgeous|',
     'Illmerica ~ Wolfgang Gartner|',
     'Mozaik - Original Mix ~ Michael Calfan|',
     'Lonely (ATOM Remix of C2C) ~ Ira May|Atom|C2C|',
     'Got a Feeling - Pleasurekraft vs. Bontan Remix ~ Josh Butler|',
     'Five Hours ~ Deorro|',
     'One Way Home - Arston Remix ~ Denzal Park|Jon Hume|',
     'Kingdom - Original Mix ~ Jewelz & Sparks|',
     'You\'ve Got The Love - Mark Knight Remix ~ Florence + The Machine|',
     'Beating Of My Heart - Matisse & Sadko Remix Edit ~ M-3ox|Heidrun|',
     'No Light, No Light - Breakage\'s One Moment Less For Mortimer Mix ~ Florence + The Machine|',
     'Heart Is King ~ Axwell|',
     'Beating Of My Heart (Matisse & Sadko Remix) / The Temper Trap ˆ Sweet Disposition ~ M-3ox feat. Heidrun|',
     'Totem ~ Tom Staar & Ansolo|Tom Staar|Ansolo|',
     'Getaway - Loudan Remix ~ X-Vertigo|Renco|Tab|',
     'The Wave - Thomas Gold Remix ~ Miike Snow|',
     'Gecko (Overdrive) - Radio Edit ~ Oliver Heldens|Becky Hill|',
     'Slenderman - Original Mix ~ Julian Jordan|',
     'We Are One ~ Tim Royko|Mike Leon|',
     'Like I Like - Tony Romera Remix ~ David Hopperman|Amanda Wilson|',
     'Alive - Original Mix ~ Funkin Matt|',
     'Heat - Original Mix ~ Vicetone|',
     'Primitive - Richard Vission Remix ~ Richard Vission|Luciana|',
     'No Heroes (feat. Luciana) - Original Mix ~ Firebeatz|KSHMR|Luciana|',
     'Feeling - Original Mix ~ Bisbetic|Angelika Vee|',
     'Codec ~ Zedd|',
     'Hourglass ~ Zedd|LIZ|',
     'Strong ~ Arno Cost & Norman Doray|Arno Cost|Norman Doray|',
     'Tear The Roof Up ~ Alesso|',
     'Avaritia ~ deadmau5|',
     'You Can Touch - Original Mix ~ John Dahlbäck|',
     'A Lot Like Love - Oliver Heldens Edit ~ The Voyagers|Haris|',
     'Fall Into The Sky ~ Zedd|Lucky Date|Ellie Goulding|',
     'Can\'t Stop Playing - Oliver Heldens & Gregor Salto Remix Edit ~ DR. KUCHO!|Gregor Salto|',
     'Celebrate The Rain - Radio Edit ~ Sidney Samson|Eva Simons|',
     'Rusty Nails ~ Moderat|',
     'We Come We Rave We Love ~ Axwell^Ingrosso|Axwell|Sebastian Ingrosso|',
     'The End (Original Mix) ~ Tommy Trash|',
     'Nightmare - Radio Edit ~ Timmy Trumpet|',
     'Ease My Mind ~ Skrillex|',
     'Turn It Around - Original Mix ~ DubVision|',
     'Happy Violence ~ Dada Life|',
     'I Can\'t Understand - Original Mix ~ Chocolate Puma|Firebeatz|',
     'Wicked - Original Mix ~ Firebeatz|Schella|',
     'A Little More ~ Kaskade|John Dahlbäck|Sansa|',
     'Faith ~ Calvin Harris|',
     'Blind Heart - Radio Edit ~ CAZZETTE|Terri B!|',
     'Heart Weighs A Ton (feat. Stefan Storm) ~ Alex Metric|Stefan Storm|',
     'Pompeii - Audien Remix ~ Bastille|',
     'Silhouettes - Original Radio Edit ~ Avicii|',
     'Top Of The World ~ The Cataracs|DEV|',
     'Atmosphere (Original Extended) ~ Kaskade|',
     'Jealous (I Ain\'t With It) - Benny Benassi Radio Edit ~ Chromeo|',
     'Silvia - Roboberget Remix ~ Miike Snow|',
     'On the Wire (Dennis Sheperd Remix) ~ Allure|Christian Burns|Dennis Sheperd|',
     'Ghost - Original Mix ~ Tom Swoon|StadiumX|Rico & Miella|',
     'You Know You Like It ~ DJ Snake & AlunaGeorge|',
     'Distraction ~ Slaptop|',
     'Wayfarer ~ Audien|',
     'Glow - Promise Land vs. AN21 & Max Vangeli Remix ~ An21|Max Vangeli|',
     'Runaway (U & I) ~ Galantis|',
     'You - Tiësto vs. Twoloud Radio Edit ~ Galantis|',
     'Faded - The Magician Remix ~ Zhu|',
     'Holding onto Heaven - Chainsmokers Remix ~ Foxes|',
     'Cannes - Radio Edit ~ Aevion|',
     'No Way Out - Radio Edit ~ Vicetone|Kat Nestel|',
     'Answers (feat. Koo) ~ Puppet|Koo|',
     'How We Gonna Stop The Time - NEW_ID Remix ~ Kraak & Smaak feat. Stee Downes|Kraak & Smaak|Stee Downes|',
     'Till It Hurts ~ Yellow Claw|Ayden|',
     'Bones (feat. HVOB) ~ Oliver Koletzki|HVOB|',
     'Forbidden Voices - Original Mix ~ Martin Garrix|',
     'Ultraviolence - Hook N Sling Remix ~ Lana Del Rey|',
     'Gold Dust ~ Galantis|',
     'Intoxicated - Radio Edit ~ Martin Solveig|GTA|',
     'Back In Time - Radio Edit ~ Don Diablo|',
     'Liar Liar - Avicii By Avicii ~ Avicii|',
     'Wicked Things - Radio Edit ~ Sander Kleinenberg|Audio Bullys|',
     'Pray to God - Calvin Harris vs Mike Pickering Hacienda Remix ~ Calvin Harris|Haim|',
     'Can You Feel It ft. Gwen McCrae - Club Mix ~ Sander Kleinenberg|',
     'You Know - Radio Edit ~ Zeds Dead|Oliver Heldens|',
     'Last All Night (Koala) [feat. KStewart] ~ Oliver Heldens|KStewart|',
     'Pikachu - Original Mix ~ Oliver Heldens|Mr. Belt & Wezol|',
     'Hypnotized - Original Version ~ Oliver Koletzki & Fran|',
     'Beggin For Thread - Gryffin & Hotel Garuda Remix ~ Banks|',
     'Never Sleep Alone ~ Kaskade|',
     'Talking Body - KREAM Remix ~ Tove Lo|',
     'The Longest Road - Deadmau5 Remix Radio Edit ~ Morgan Page|Lissie|',
     'Sunrise (feat. Sara Kay) ~ Klaypex|',
     'Real Love (feat. Danyka Nadeau) ~ Rootkit|Danyka Nadeau|',
     'Hey Baby - Original Mix ~ deadmau5|Melleefresh|',
     'Natural Disaster ~ Laidback Luke|Example|',
     'Magic - Arston Remix ~ Olympic Ayres|',
     'Spectrum (Say My Name) - Calvin Harris Remix ~ Florence + The Machine|',
     'The End ~ Seven Lions|HALIENE|',
     'Overdrive ~ Calvin Harris|Ummet Ozcan|',
     'One Touch VIP (feat. AlunaGeorge) ~ Baauer|AlunaGeorge|',
     'Secrets - Radio Edit ~ Tiësto|KSHMR|Vassy|',
     'New Scene (feat. Ofelia) - Original Mix ~ Felix Cartal|Ofelia|',
     'How Bad Do You Want It (Oh Yeah) ~ Sevyn Streeter|',
     'Freeze Time - Original Mix ~ Manse|Alice Berg|',
     'Stronger ~ Arty|Ray Dalton|',
     'Bloodstream - Arty Remix ~ Ed Sheeran|Rudimental|',
     'We Make It Bounce ~ Dillon Francis|Major Lazer|Stylo G|',
     'Every Single Piece - Radio Mix ~ Redondo|Bolier|She Keeps Bees|',
     'Furious Angels - Furious Angels ~ Rob Dougan|',
     'Papercut ~ Zedd|Troye Sivan|',
     'Together - Radio Edit ~ CAZZETTE|Newtimers|',
     'Some Minds ~ Flume|Andrew Wyatt|',
     'Be Together (feat. Wild Belle) ~ Major Lazer|Wild Belle|',
     'Roll the Bass ~ Major Lazer|',
     'Peanut Butter Jelly ~ Galantis|',
     'Runaway (U & I) - Kaskade Remix ~ Galantis|',
     'Beam Me Up - Radio Edit ~ CAZZETTE|',
     'Kill \'Em With The Love ~ Galantis|',
     'No Ordinary Life (feat. Angela McCluskey) ~ Morgan Page|Angela McCluskey|',
     'Foundation ~ Years & Years|',
     'The Girl (feat. Cozi Zuehlsdorff) ~ Hellberg|Cozi Zuehlsdorff|',
     'I Wanna Be Your Dog - Brockman & Basti M Re-Edit ~ Swanky Tunes|Hard Rock Sofa|',
     'Cool Enough - Radio Edit ~ Spada|Elen Levon|',
     'Collide - Radio Edit ~ Third Party|Daniel Gidlund|',
     'Can\'t Sleep - Marcus Schossow\'s Radio Edit ~ Adrian Lux|',
     'I Found U - Radio Edit ~ Axwell|',
     'Leave The World Behind - Radio Edit ~ Axwell|Sebastian Ingrosso|Steve Angello|Laidback Luke|Deborah Cox|',
     'Together - Original Mix ~ The Magician|',
     'ILYSB - Ferdinand Weber Edit ~ LANY|',
     'Cool - Sonny Alven Remix ~ Alesso|Roy English|',
     'Lullabies - Adventure Club Remix ~ Yuna|',
     'Stay (feat. deadmau5) - Drop The Poptart Edit ~ Colleen D\'agostino|deadmau5|',
     'The Wall (Radio Edit) [feat. Kat Cobra] ~ Oskar|Ken Loi|Kat Cobra|',
     'Mercy - Radio Edit ~ Michael Calfan|',
     'Atmosphere - Radio Edit ~ Kaskade|',
     'Crave You - Adventure Club Remix ~ Flight Facilities|',
     'How Deep Is Your Love ~ Calvin Harris|Disciples|',
     'Get Get Down - Original Mix ~ Merk & Kremont|',
     'Lost You ~ Zeds Dead|Twin Shadow|D\' Angelo Lacy|',
     'High - Yahtzel Remix ~ Peking Duk|Nicole Millar|',
     'You Could Be Happy - Paul Oakenfold Future House Radio Edit ~ Paul Oakenfold|Angela McCluskey|' ],
  'kairos 118': 
   [ 'Float On ~ Modest Mouse|',
     'Cello Suite No. 1 in G Major, BMV 1007: Prelude ~ Jorg Metzger|',
     'I Saw God Today ~ George Strait|',
     'If Heaven Wasn\'t So Far Away ~ Justin Moore|',
     'Eye of the Tiger ~ Survivor|',
     'Vivir Mi Vida ~ Marc Anthony|',
     'Love Never Fails ~ Brandon Heath|',
     'Morning Has Broken ~ Cat Stevens|',
     'Brave ~ Sara Bareilles|',
     'Mad World ~ Michael Andrews|Gary Jules|',
     'Someone Call An Angel Down ~ Derek Miller|',
     'Ooh Ahh (My Life Be Like) (feat. Toby Mac) ~ Grits|TobyMac|',
     'Pompeii ~ Bastille|',
     'Reflection Eternal ~ Nujabes|',
     'Man in the Mirror - Remastered Version ~ Michael Jackson|',
     'Over the Rainbow / What a Wonderful World ~ Israel Kamakawiwo\'ole|',
     'By Your Side ~ Tenth Avenue North|',
     'I\'ll Be There ~ Jackson 5|',
     'Somewhere Only We Know ~ Lily Allen|' ],
  'house.': 
   [ 'Call My Name (Spencer & Hill Radio Edit) (feat. Nadia Ali) ~ Nadia Ali|',
     'Levels - Radio Edit ~ Avicii|',
     'Turbulence - Radio Edit ~ Steve Aoki|Laidback Luke|Lil Jon|',
     'Give It Up For Me ~ Sydney Blu|',
     'Let\'s Get Bleeped Tonight - Mustard Pimp Remix ~ Dada Life|',
     'Space Junk ~ Wolfgang Gartner|',
     'One (Your Name) [feat. Pharrell] [Radio Edit] ~ Swedish House Mafia|Pharrell Williams|',
     'Take Me With You ~ Serge Devant|',
     'We No Speak Americano - Radio Edit ~ Yolanda Be Cool|DCup|',
     'Pressure - Alesso Remix ~ Nadia Ali|Starkillers|Alex Kenji|',
     'Epic ~ Sandro Silva & Quintino|',
     'Navy Seals 2012 (feat. Freddy Genius) ~ Mikkel Christiansen|',
     'Miami 2 Ibiza ~ Swedish House Mafia|Tinie Tempah|',
     'Replica - Original Mix ~ Afrojack|',
     'The black Pearl - Dave Darell Radio Edit ~ Scotty|',
     'Hangover ~ Taio Cruz|Flo Rida|',
     'Dreamscape ~ 009 Sound System|',
     'Zero 76 ~ Tiësto & Hardwell|',
     'Take A Moment - Alex M.O.R.P.H. Remix ~ Armin van Buuren|Winter Kills|',
     'Hold on (Don & Palm Remix) ~ Fredrik Nyberg|',
     'Close To Me ~ Benny Benassi|Gary Go|',
     'Fallen Angel [Mix Cut] - Dennis Sheperd Club Mix ~ Dennis Sheperd|Cold Blue|Ana Criado|',
     'Beggin\' You - Armin van Buuren Remix ~ Cerf|Mitiska|Jaren|',
     'Pacific Coast Highway ~ Wentworth & Mordemere|',
     'Some Chords ~ deadmau5|',
     'Ray Ban Vision ~ A-Trak|Cyhi Da Prynce|',
     'Unison ~ Porter Robinson|',
     'No Beef - Vocal Mix ~ Afrojack|Steve Aoki|Miss Palmer|',
     'Paradise Poltergeist ~ Tai|Steve Aoki|',
     'Madagascar - Original Mix ~ Dimitri Vegas & Like Mike|Yves V|Angger Dimas|',
     'One - Radio Edit ~ Swedish House Mafia|',
     'We Run The Night ~ Havana Brown|Pitbull|',
     'Cudi The Kid - feat. Kid Cudi & Travis Barker ~ Steve Aoki|',
     'Generation 303 (Original Mix) ~ Nicky Romero|',
     'Wild Ones (feat. Sia) ~ Flo Rida|Sia|',
     'Greyhound ~ Swedish House Mafia|',
     'Where Have You Been ~ Rihanna|',
     'Levels - Skrillex Remix ~ Avicii|',
     'REJ - Original Mix ~ Dimitri Vegas & Like Mike|',
     'Calling (Lose My Mind) - Radio Edit ~ Sebastian Ingrosso|Alesso|Ryan Tedder|',
     'Mirage ~ Pryda|',
     'The End (Original Mix) ~ Tommy Trash|',
     'Feel So Close - Benny Benassi Remix ~ Calvin Harris|',
     'Dirty Talk - Laidback Luke Remix ~ Wynter Gordon|',
     'Love Is Darkness - Radio Edit ~ Sander van Doorn feat. Carol Lee|',
     'Where The Wild Things Are ~ Far East Movement|Crystal Kay|',
     'I Can Only Imagine (feat. Chris Brown & Lil Wayne) ~ David Guetta|Lil Wayne|Chris Brown|',
     'The Island - Pt. I (Dawn) ~ Pendulum|',
     'The Island - Pt. II (Dusk) ~ Pendulum|',
     'In My Mind (feat. Georgi Kay) - Axwell Radio Edit ~ Ivan Gough|Feenixpawl|Georgi Kay|',
     'Atom - Original Mix ~ Nari|Milani|',
     'Walking Alone ~ Dirty South & Those Usual Suspects feat Erik Hecht|Dirty South|Those Usual Suspects|Erik Hecht|',
     'The Way We See The World - Tomorrowland Anthem Instrumental ~ Afrojack|Dimitri Vegas & Like Mike|NERVO|',
     'Beating Of My Heart - Matisse & Sadko Remix ~ M-3ox|Heidrun|',
     'Freestyle ~ Bassnectar|Angel Haze|',
     'Here We Go ~ Hard Rock Sofa|Swanky Tunes|',
     'Guilty Pleasure - 3LAU Bootleg ~ 3LAU|',
     'Phat Brahms (Steve Aoki & Angger Dimas vs. Dimitri Vegas & Like Mike) ~ Steve Aoki|Angger Dimas|Dimitri Vegas & Like Mike|',
     'Kick Out The Epic Motherf**ker ~ Dada Life|',
     'Feed The Dada ~ Dada Life|',
     'You Will Do What We Will Do ~ Dada Life|',
     'Just One Last Time (feat. Taped Rai) ~ David Guetta|Taped Rai|',
     'Hourglass ~ Zedd|LIZ|',
     'Clarity ~ Zedd|Foxes|',
     'Spectrum - Radio Mix ~ Zedd|Matthew Koma|',
     'I Could Be The One [Avicii vs Nicky Romero] - Nicktim - Radio Edit ~ Avicii|Nicky Romero|',
     'Harlem Shake ~ Baauer|',
     'Years - Radio Edit ~ Alesso|Matthew Koma|',
     'Down The Road ~ C2C|',
     'Beam Me Up (Kill Mode) (Radio Edit) ~ CAZZETTE|',
     'Graduation ~ Gemini|',
     'Oxygen - Gemini Remix ~ Hadouken!|',
     'Rise & Fall ~ Gemini|',
     'Seventeen - Skrillex AKA Sonny Moore Remix ~ Casxio|',
     'Set It Off (feat. Lazerdisk Party Sex) ~ Diplo feat. Lazerdisk Party Sex|Diplo|Lazerdisk Party Sex|',
     'Express Yourself (feat. Nicky Da B) ~ Diplo feat. Nicky Da B|Diplo|Nicky Da B|',
     'Tokyo ~ Gareth Emery|',
     'So Young So High ~ Dada Life|',
     'Clash - Original Mix ~ Alesso|',
     'Sweet Nothing (Diplo + Grandtheft Remix) ~ Calvin Harris feat. Florence Welch|',
     'Right On Time ~ Skrillex|12th Planet|Kill The Noise|',
     'Goin\' In - Skrillex "Goin\' Hard" Mix ~ Birdy Nam Nam|',
     'This Is Love ~ will.i.am|Eva Simons|',
     'Gettin\' Dumb ~ will.i.am|apl.de.ap|2NE1|',
     'Kyoto (feat. Sirah) ~ Skrillex|Sirah|',
     'Rattle - Original Mix ~ Bingo Players|',
     'Reload - Vocal Version / Radio Edit ~ Sebastian Ingrosso|Tommy Trash|John Martin|',
     'Partysaurus Overflow (inspired by "Partysaurus Rex") - (Inspired by "Partysaurus Rex") ~ BT|Au5|',
     'Skylarking - Radio Edit ~ BT|',
     'Must Be The Love - Shogun Radio Edit ~ Arty|Nadia Ali|BT|',
     'A Little Party Never Killed Nobody (All We Got) ~ Fergie|Q-Tip|GoonRock|',
     'Sunrise (Won\'t Get Lost) - Tommy Trash Radio Edit ~ The Aston Shuffle|Tommy Trash|',
     'I Love The Feeling ~ D.VELOPED|',
     'D.composed Vol. 4 ~ D.VELOPED|',
     'Summertime Sadness [Lana Del Rey vs. Cedric Gervais] - Cedric Gervais Remix ~ Lana Del Rey|Cedric Gervais|',
     'Animals ~ Martin Garrix|',
     'Hell Yeah! ~ Tiësto & Showtek|',
     'Long Time - Radio Edit ~ John De Sohn|Andreas Moe|',
     'Pair of Dice (Radio Edit) ~ Tiësto|Allure|',
     'Ladi Dadi - Tommy Trash Remix ~ Steve Aoki|Wynter Gordon|',
     'Svenska - Radio Edit ~ Matisse & Sadko|',
     '4 AM - Radio Version ~ Scooter|',
     'Burn ~ Ellie Goulding|',
     'Watch Out For This [Bumaye] [feat. Busy Signal, The Flexican & FS Green] - feat. Busy Signal, The Flexican & FS Green ~ Major Lazer|FS Green|The Flexican|Busy Signal|',
     'D.composed Vol. 2 ~ D.VELOPED|',
     'D.composed Vol. 3 ~ D.VELOPED|',
     'Totally Recalled ~ D.VELOPED|',
     'Locked Out Of Heaven - Sultan and Ned Shepard Remix ~ Bruno Mars|',
     'Get Loose - Tiësto Remix ~ Showtek|Noisecontrollers|',
     'Mammoth - Original Mix ~ Dimitri Vegas & Like Mike|Moguai|Like Mike|',
     'Ain\'t A Party [feat. Harrison] - Radio Edit ~ David Guetta|GLOWINTHEDARK|Harrison|',
     'Tsunami - Original Mix ~ Dvbbs|Borgeous|',
     'Voltage - Original Mix ~ Danny Avila|',
     'Project T - Original Mix ~ Dimitri Vegas & Like Mike|Sander Van Doorn|',
     'Boy Oh Boy ~ Diplo & GTA|Diplo|GTA|',
     'Hey Brother ~ Avicii|',
     'Bird Machine ~ DJ Snake feat. Alesia|DJ Snake|Alesia|',
     'Youth (Adventure Club Remix) ~ Foxes|',
     'If I Lose Myself - Alesso vs OneRepublic ~ OneRepublic|Alesso|',
     'Snake - Original Mix ~ BlasterJaxx|',
     'Turn Down for What ~ DJ Snake|Lil Jon|',
     'Get Low ~ Dillon Francis|DJ Snake|',
     'Stop In My Mind - Original Mix ~ Hard Rock Sofa|Swanky Tunes|',
     'Boneless ~ Steve Aoki|Chris Lake|Tujamo|',
     'Recess (feat. Fatman Scoop and Michael Angelakos) - Ape Drums Remix ~ Skrillex|Kill The Noise|Michael Angelakos|Fatman Scoop|',
     'Find You - Kevin Drew Remix ~ Zedd|Matthew Koma|Miriam Bryant|',
     'Rude - Zedd Remix ~ Magic!|',
     'Lose Yourself (feat. RDX & Moska) ~ Major Lazer|',
     'You & Me - Flume Remix ~ Disclosure|Eliza Doolittle|',
     'Five Hours ~ Deorro|',
     'Like Satellites (Radio Edit) ~ Manufactured Superstars|Danni Rouge|',
     'Heroes (we could be) - Branchez Remix ~ Alesso|Tove Lo|',
     'GDFR (feat. Sage The Gemini & Lookas) ~ Flo Rida|Lookas|Sage The Gemini|',
     'Runaway (U & I) ~ Galantis|',
     'You Make Me ~ Avicii|',
     'Gold Skies ~ Sander Van Doorn|Martin Garrix|Dvbbs|Aleesia|',
     'Payback ~ Dimitri Vangelis & Wyman|Steve Angello|',
     'King Cobra ~ Yves V|Don Diablo|',
     'A Sky Full of Stars - Hardwell Remix ~ Coldplay|',
     'Ping Pong - Hardwell Radio Edit ~ Armin van Buuren|Hardwell|',
     'Magic ~ Yves V|Sidney Samson|',
     'Don\'t Stop the Madness ~ Hardwell|W&W|Fatman Scoop|',
     'Bullit ~ Watermät|',
     'I Love It When You Cry (Moxoki) - Radio Edit ~ Steve Aoki|Moxie Raia|',
     'Together (In A State Of Trance) - Original Mix ~ Armin van Buuren|',
     'Bitch I\'m Madonna ~ Madonna|Nicki Minaj|',
     'Hit It ~ Deorro|Dirty Audio|I-Ez|',
     'Close Your Eyes (And Count to Fuck) [feat. Zack De La Rocha] ~ Run The Jewels|',
     'Scylla ~ RL Grime|',
     'Another You ~ Armin van Buuren|Mr. Probz|',
     'Louder - Radio Edit ~ Dimitri Vegas & Like Mike|Vinai|',
     'Smile ~ Galantis|',
     'The Nights ~ Avicii|' ],
  'Vitamin String Quartet': 
   [ 'Attack ~ Vitamin String Quartet|',
     'Hell Song ~ Vitamin String Quartet|',
     'Mr. Brightside ~ Vitamin String Quartet|',
     'The Kids Aren\'t Alright ~ Vitamin String Quartet|',
     'Californication ~ Vitamin String Quartet|',
     'Ocean Avenue ~ Vitamin String Quartet|',
     'Snow (Hey Oh) - Tribute to Red Hot Chili Peppers ~ Vitamin String Quartet|',
     'Never Too Late (String Quartet Tribute to Three Days Grace) ~ Vitamin String Quartet|',
     'Animal I Have Become - Tribute to Three Days Grace ~ Vitamin String Quartet|',
     'Diary of Jane - Tribute to Breaking Benjamin ~ Vitamin String Quartet|',
     'In the End - Linkin Park ~ Vitamin String Quartet|',
     'Leave Out All The Rest ~ Vitamin String Quartet|',
     'What I\'ve Done - String Quartet Tribute to Linkin Park ~ Vitamin String Quartet|',
     'Viva La Vida ~ Vitamin String Quartet|',
     'Boulevard of Broken Dreams ~ Vitamin String Quartet|',
     'Fireflies ~ Vitamin String Quartet|',
     'Wonderwall - String Quartet Tribute to Oasis ~ Vitamin String Quartet|',
     'Hey, Soul Sister - Originally performed by Train ~ Vitamin String Quartet|',
     'Poker Face ~ Vitamin String Quartet|',
     'Scars ~ Vitamin String Quartet|',
     'Iris : The String Quartet Tribute to Goo Goo Dolls ~ Vitamin String Quartet|',
     'Last Resort ~ Vitamin String Quartet|',
     'Dear Mama ~ Vitamin String Quartet|',
     'Hedwig\'s Theme ~ Vitamin String Quartet|',
     'Hey There, Delilah ~ Vitamin String Quartet|',
     'Lose Yourself - String Quartet Tribute to Eminem ~ Vitamin String Quartet|',
     'We Will Rock You ~ Vitamin String Quartet|',
     'We Are the Champions ~ Vitamin String Quartet|',
     'Don’t Stop Believin’ ~ Vitamin String Quartet|',
     'California Love ~ Vitamin String Quartet|',
     'Prayer of the Refugee ~ Vitamin String Quartet|',
     'Faint ~ Vitamin String Quartet|',
     'Somewhere I Belong ~ Vitamin String Quartet|',
     'Wake Me Up When September Ends ~ Vitamin String Quartet|',
     'Use Somebody ~ Vitamin String Quartet|',
     'Hide and Seek ~ Vitamin String Quartet|',
     'Speeding Cars ~ Vitamin String Quartet|',
     'Headlock ~ Vitamin String Quartet|',
     'Goodnight and Go ~ Vitamin String Quartet|',
     'First Train Home ~ Vitamin String Quartet|',
     'Candlelight ~ Vitamin String Quartet|',
     'Lifeline ~ Vitamin String Quartet|',
     'Bittersweet Symphony (Instrumental) ~ The Aranbee Pop Symphony Orchestra|' ],
  '#TD4W (Best of House)': 
   [ 'Move To The Rhythm - Original Mix ~ Tiësto|Nari & Milani|Delayers|',
     'In My Mind (feat. Georgi Kay) - Axwell Radio Edit ~ Ivan Gough|Feenixpawl|Georgi Kay|',
     'The Final Countdown - Original mix ~ Marc MacRowland|',
     'Reload - Vocal Version / Radio Edit ~ Sebastian Ingrosso|Tommy Trash|John Martin|',
     'Turn Back Time - Radio Edit ~ Sub Focus|',
     'Let Your Mind Go - Radio Edit ~ Michael Calfan|John Dahlbäck|Andy P|',
     'Under Control ~ Calvin Harris|Alesso|Hurts|',
     'Buming Boombox - Original Mix ~ Rune RK|',
     'We Own the Night - Original Mix ~ Tiësto|Wolfgang Gartner|Luciana|',
     'Nillionaire ~ Alesso|',
     'Red Lights - twoloud Remix ~ Tiësto|',
     'People Of The Night - Dimitri Vangelis & Wyman Remix ~ An21|Max Vangeli|Tiësto|Lover Lover|',
     'As Long As I\'m Alive - Original ~ Brass Knuckles|John Ryan|',
     'The Buzz - Original Mix Edit ~ New World Sound|Timmy Trumpet|',
     'Lonely (ATOM Remix of C2C) ~ Ira May|Atom|C2C|',
     'Illmerica ~ Wolfgang Gartner|',
     'Wildfire - Radio Edit ~ Borgeous|',
     'Gecko (Overdrive) - Radio Edit ~ Oliver Heldens|Becky Hill|',
     'Turn Back Time [Remix] ~ Sub Focus|' ] }
